include(CTest)
function(add_io_test TEST_NAME TEST_SRC)
    add_executable(${TEST_NAME} ${TEST_SRC})
    target_include_directories(${TEST_NAME} PRIVATE include)
    target_link_libraries(${TEST_NAME} PRIVATE iostreams)
    target_compile_features(${TEST_NAME} PRIVATE cxx_std_20)
    add_test(NAME ${TEST_NAME} COMMAND $<TARGET_FILE_DIR:${TEST_NAME}>/${TEST_NAME}${TEST_EXT})
endfunction()
add_io_test(archive_stream tests/archive_stream.cpp)