include(CTest)
function(add_io_test TEST_NAME TEST_SRC)
    add_executable(${TEST_NAME} ${TEST_SRC})
    target_include_directories(${TEST_NAME} PRIVATE include)
    target_link_libraries(${TEST_NAME} PRIVATE iostreams Catch2::Catch2WithMain)
    target_compile_features(${TEST_NAME} PRIVATE cxx_std_20)
    add_test(NAME ${TEST_NAME} COMMAND $<TARGET_FILE_DIR:${TEST_NAME}>/${TEST_NAME}${TEST_EXT})
endfunction()
add_io_test(archive_stream tests/archive_stream.cpp)
add_io_test(serial_tests tests/serial_tests.cpp)
add_io_test(http_parsing_tests tests/http_parsing_tests.cpp)
add_io_test(ip_validation_tests tests/ip_validation_tests.cpp)
add_io_test(streambuf_tests tests/streambuf_tests.cpp)
add_io_test(tcp_tests tests/tcp_tests.cpp)
add_io_test(udp_tests tests/udp_tests.cpp)
add_io_test(serial_advanced_tests tests/serial_advanced_tests.cpp)
add_io_test(utility_tests tests/utility_tests.cpp)
add_io_test(ssl_tests tests/ssl_tests.cpp)
add_io_test(udpmc_tests tests/udpmc_tests.cpp)
add_io_test(archive_tests tests/archive_tests.cpp)
add_io_test(ringbuf_advanced_tests tests/ringbuf_advanced_tests.cpp)
add_io_test(http_live_tests tests/http_live_tests.cpp)
